spring.application.name=ConfigServer


server.port=8888
spring.cloud.config.server.git.uri=https://github.com/aniltiw/ConfigServer


spring.cloud.config.server.git.searchPaths=third-service-config
spring.cloud.config.server.git.username =aniltiw
spring.cloud.config.server.git.password = Th1nkf1nance
spring.cloud.config.server.git.clone-on-start=true
